apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "donox"
  description: "donox"
  annotations:
    github.com/project-slug: techtalk-1123/donox
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/guests"
